apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-hellospa
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: cluster
    repoURL: https://github.com/MADRAFi/hello-spa-config.git
    targetRevision: HEAD